# Generated by Django 5.0.5 on 2024-05-06 19:07

import code_analysis.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_codesnippetimage_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_snippet', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_results', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
                ('code_snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_analysis.codesnippet')),
            ],
        ),
        migrations.CreateModel(
            name='CustomAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatted_code', models.TextField(blank=True, null=True)),
                ('analysis_results1', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_analysis.codesnippet')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('error', 'Error'), ('complexity', 'Complexity'), ('explanation', 'Explanation')], default='explanation', max_length=20)),
                ('message', models.TextField(default='Hello there seems to be an error analysisng your codeS')),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(default=code_analysis.models.get_dummy_analysis, on_delete=django.db.models.deletion.CASCADE, to='code_analysis.analysis')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
