# Generated by Django 5.0.3 on 2024-04-14 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customanalysis',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='customanalysis',
            name='analysis_type',
        ),
    ]
