# Generated by Django 5.0.3 on 2024-04-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_analysis', '0002_remove_customanalysis_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customanalysis',
            name='formatted_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
